#!/bin/bash

if [[ $CONFIGURATION == "Release" ]]; then
    KEY=$(node "${BASH_SOURCE%/*}"/../generate-aes256-key.js)

    # save the key in a file because we need it in the post-build script as well
    echo $KEY > key.txt

    # change the header and save main.m to main.m.bak
    sed -i '.bak' 's/#include <TNSExceptionHandler.h>/#include <TNSExceptionHandler.h>\
#include <TNSAppProtection.h>/g' $SRCROOT/internal/main.m    
    
    # change the header and save main.m to main.m.bak2 (so main.m.bak is still the real backup)
    sed -i '.bak2' 's#TNSInstallExceptionHandler();#TNSInstallExceptionHandler();\
    [TNSAppProtection setKey:[[NSData alloc] initWithBase64EncodedString:@"'$KEY'" options:0]];#g' $SRCROOT/internal/main.m    
fi