#!/bin/bash

if [[ $CONFIGURATION == "Release" ]]; then
    # read the key from the file we saved it to in the pre-build script
    KEY=`cat k`

    # encrypt the app's .js files
    APP_FOLDER="$CONFIGURATION_BUILD_DIR/$CONTENTS_FOLDER_PATH/app"
    FILES=$(find "$APP_FOLDER" -not \( -path "$APP_FOLDER/tns_modules" -prune \) -name '*.js' -type f)
    for f in $FILES
    do
        node "${BASH_SOURCE%/*}"/../../scripts/encrypt-file.js $KEY "${f/$APP_FOLDER/$PROJECT_DIR/$PROJECT_NAME/app}" "$f"
    done
fi

# we no longer need the key file
rm k